services:
  frontend:
    name: frontend
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:frontend-prod-f30be4afe0562e36479aeb49133e260537d135b3
    port: 80
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  product:
    name: product-service
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:product-service-prod-f30be4afe0562e36479aeb49133e260537d135b3
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      uri: mongodb://mongodb:27017/product-service
  order:
    name: order-service
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:order-service-prod-f30be4afe0562e36479aeb49133e260537d135b3
    port: 8081
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      uri: mongodb://mongodb:27017/order-service
mongodb:
  enabled: true
  name: mongodb
  image: mongo:latest
  port: 27017
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
