apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microstore-staging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/nadavcool543/MicroStore.git
      targetRevision: staging
      path: helm
      helm:
        valueFiles:
          - $values/environments/staging/values.yaml
    - repoURL: https://github.com/nadavcool543/gitops-repo.git
      targetRevision: HEAD
      path: .
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 