# Global Values
environment: dev
domain: nshohat.online
clusterName: dev-eks-cluster
services:
  frontend:
    name: frontend
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:frontend-dev-a3067ce7589cc05226fca1708630f9cc8b8fb3b3
    port: 80
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  product:
    name: product-service
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:product-service-dev-a3067ce7589cc05226fca1708630f9cc8b8fb3b3
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      secretName: documentdb-credentials
      secretKey: MONGODB_URI
      dbName: product-service
  order:
    name: order-service
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:order-service-dev-a3067ce7589cc05226fca1708630f9cc8b8fb3b3
    port: 8081
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      secretName: documentdb-credentials
      secretKey: MONGODB_URI
      dbName: order-service
# Disable local MongoDB since we're using DocumentDB
mongodb:
  enabled: false
# External Secrets Configuration
aws:
  region: us-east-1
externalSecrets:
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
documentdb:
  secretName: documentdb-credentials
  namespace: dev
  refreshInterval: 1h
  awsSecretKey: app/dev/microstore-v6
