# Global Values
environment: dev
domain: nshohat.online
clusterName: dev-eks-cluster

# Monitoring Configuration
monitoring:
  interval: 30s

services:
  frontend:
    name: frontend
    image: "767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:frontend-dev-3cd1be384327843a6f90808eb8c0fdeddcc24388"
    port: 80
    replicas: 1
    probes:
      readiness:
        initialDelay: 10
        period: 5
        timeout: 2
        successThreshold: 1
        failureThreshold: 3
      liveness:
        initialDelay: 15
        period: 10
        timeout: 2
        successThreshold: 1
        failureThreshold: 3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  product:
    name: product-service
    image: "767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:product-service-dev-3cd1be384327843a6f90808eb8c0fdeddcc24388"
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      secretName: documentdb-credentials
      secretKey: MONGODB_URI
      dbName: product-service
  order:
    name: order-service
    image: "767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:order-service-dev-3cd1be384327843a6f90808eb8c0fdeddcc24388"
    port: 8081
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      secretName: documentdb-credentials
      secretKey: MONGODB_URI
      dbName: order-service

# External Secrets Configuration
aws:
  region: us-east-1
externalSecrets:
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
documentdb:
  secretName: documentdb-credentials
  namespace: dev
  refreshInterval: 1h
  awsSecretKey: app/dev/microstore-v6
