# Global Values
environment: dev
domain: nshohat.online
clusterName: dev-eks-cluster
services:
  frontend:
    name: frontend
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:frontend-dev-0cb14fb4957c2720e6184ca5deebdf2649c8a5bf
    port: 80
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  product:
    name: product-service
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:product-service-dev-0cb14fb4957c2720e6184ca5deebdf2649c8a5bf
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      secretName: documentdb-credentials
      secretKey: MONGODB_URI
      dbName: product-service
  order:
    name: order-service
    image: 767397741479.dkr.ecr.us-east-1.amazonaws.com/microstore:order-service-dev-0cb14fb4957c2720e6184ca5deebdf2649c8a5bf
    port: 8081
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mongodb:
      secretName: documentdb-credentials
      secretKey: MONGODB_URI
      dbName: order-service
# Disable local MongoDB since we're using DocumentDB
mongodb:
  enabled: false
